### ISSUE TITLE
vrpn conflicts with rqt_graph for ROS Melodic

### ISSUE THREAD

**Issue by vigyansadhu** [clearpathrobotics/vrpn_ros#14]
Below is the command line prompt. I wanted to view the rqt_graph after running vrpn node. The vrpn node runs fine in ROS and I am able to view the rqt_graph if no data is being sent from Motive (optitrack). But, if data is being sent from motive, the rqt_graph aborts and shows the below error.

#############################
rospc@avl2:~/catkin_ws$ rqt_graph
PluginHandlerDirect._restore_settings() plugin "rqt_graph/RosGraph#0" raised an exception:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 116, in _restore_settings
    self._plugin.restore_settings(plugin_settings_plugin, instance_settings_plugin)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 217, in restore_settings
    self._refresh_rosgraph()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 246, in _refresh_rosgraph
    self._update_graph_view(self._generate_dotcode())
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 280, in _generate_dotcode
    hide_dynamic_reconfigure=hide_dynamic_reconfigure)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_graph/dotcode.py", line 876, in generate_dotcode
    hide_dynamic_reconfigure=hide_dynamic_reconfigure)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_graph/dotcode.py", line 700, in generate_dotgraph
    nt_nodes, edges, tf_connections = self._group_tf_nodes(nt_nodes, edges, node_connections)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_graph/dotcode.py", line 513, in _group_tf_nodes
    tf_topic_edges_in.update([x for x in node_connections[n].incoming if x in edges and x.end in nodes])
KeyError: ' /tf'
########################

**Comment by paulbovbel** [comment]
This doesn't sound specifically like a vrpn_client_ros issue. Please try posting in answer.ros.org, with more details about your environment.
